### ISSUE TITLE
Address is not properly detected when it's switched

### ISSUE THREAD

**Issue by sembrestels** [CommonsSwarm/tec-convert#6]
Steps to reproduce:
1. Enable account with Account 1
2. Switch to Account 2 with metamask
3. Convert some bonded tokens to collateral (TEC to xDAI)
4. The transaction can not be done because Account 2 is not detected
![Screenshot from 2020-11-14 11-52-02](https://user-images.githubusercontent.com/931684/99145509-e29b8380-266f-11eb-8fd7-faa8306abfe2.png)
![Screenshot from 2020-11-14 11-52-22](https://user-images.githubusercontent.com/931684/99145511-e4fddd80-266f-11eb-8f33-6c74728789e3.png)

**Comment by daithi-coombes** [comment]
Was only able to recreate once last night. Haven't been able to so since.

Have tried ff, chromium, brave and only recreated once with Brave. Have found [this issue](https://ethereum.stackexchange.com/questions/88101/invalid-parameters-must-provide-an-ethereum-address-code-32602) but although same error I don't think its because of a bad payload, as it the error would then persist. (answer got 3 ups).

Also the latest metamask (in ff) gives option to switch account when doing step 2 in OP.
Running the master branch of `convert`

@sembrestels can you still recreate this? If so what browser/metamask & os were you using?
Also is there a deployed version of convert that the issue is persistent in (maybe npm is using different web3/dependency on my local)

**Comment by GriffGreen** [comment]
weird!

**Comment by vivianedias** [comment]
@sembrestels I dont think this issue is a problem anymore, because Metamask ignores if you changed accounts and only signals that you are connected to one but switched in the app.

The user flow is to just do the transaction with the selected account in the app.

**Comment by marthendalnunes** [comment]
@mendesfabio @PabloCGL can you guys reproduce this error? I've been trying here but it seems to work fine.

**Comment by sembrestels** [comment]
It should be fixed by 26dc66c88d1740ce5ced529afc907f2a20eaf2f7.
